/*
 * FASE 12
 *
 * Fundação persistente da orquestração e do processamento assíncrono.
 *
 * Objetivos:
 *
 * 1. representar uma execução de coleta;
 * 2. preservar candidatos já parseados para que enrichment possa
 *    ser repetido sem repetir a coleta;
 * 3. representar jobs duráveis;
 * 4. permitir retry;
 * 5. permitir claim concorrente por múltiplos workers;
 * 6. preservar idempotência por etapa;
 * 7. registrar falhas sem misturar regras de negócio com a fila.
 *
 * Esta migration NÃO implementa scheduler.
 * Esta migration NÃO implementa publicação.
 * Esta migration NÃO executa regra comercial.
 */


/* ================================================================
 * PROCESSING RUN
 * ================================================================ */

CREATE TABLE processing_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /*
     * Identidade idempotente fornecida pela aplicação para uma
     * execução lógica de coleta.
     */
    run_key TEXT NOT NULL,

    /*
     * Origem solicitada para a coleta.
     */
    source_uri TEXT NOT NULL,

    status TEXT NOT NULL,

    requested_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,

    last_error_code TEXT,
    last_error_message TEXT,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_processing_run_key
        UNIQUE (run_key),

    CONSTRAINT ck_processing_run_status
        CHECK (
            status IN (
                'PENDING',
                'RUNNING',
                'COMPLETED',
                'FAILED'
            )
        )
);


/* ================================================================
 * DEAL CANDIDATE
 * ================================================================ */

/*
 * Representa o resultado durável do parsing.
 *
 * A existência desta tabela é importante porque a FASE 12 exige
 * que uma falha posterior no enrichment não obrigue uma nova coleta.
 *
 * Ela armazena fatos produzidos por ParsedDeal.
 *
 * Não contém seller/delivery porque esses dados pertencem ao
 * enrichment da página individual.
 */
CREATE TABLE deal_candidate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    processing_run_id BIGINT NOT NULL,

    asin VARCHAR(10) NOT NULL,
    product_url TEXT NOT NULL,
    title TEXT NOT NULL,
    image_url TEXT,

    current_price NUMERIC NOT NULL,
    basis_price NUMERIC,
    previous_price NUMERIC,

    sold_percentage NUMERIC,
    rating NUMERIC,
    review_count BIGINT,

    collected_at TIMESTAMPTZ NOT NULL,
    source TEXT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_deal_candidate_processing_run
        FOREIGN KEY (processing_run_id)
        REFERENCES processing_run (id),

    /*
     * Dentro da mesma execução, a mesma observação normalizada não
     * deve gerar candidatos duplicados.
     */
    CONSTRAINT uq_deal_candidate_observation
        UNIQUE (
            processing_run_id,
            asin,
            collected_at,
            source
        ),

    CONSTRAINT ck_deal_candidate_asin
        CHECK (
            CHAR_LENGTH(asin) = 10
        ),

    CONSTRAINT ck_deal_candidate_sold_percentage
        CHECK (
            sold_percentage IS NULL
            OR (
                sold_percentage >= 0
                AND sold_percentage <= 100
            )
        ),

    CONSTRAINT ck_deal_candidate_rating
        CHECK (
            rating IS NULL
            OR (
                rating >= 0
                AND rating <= 5
            )
        ),

    CONSTRAINT ck_deal_candidate_review_count
        CHECK (
            review_count IS NULL
            OR review_count >= 0
        )
);


/* ================================================================
 * PROCESSING JOB
 * ================================================================ */

/*
 * Fila persistente.
 *
 * Nesta fase os tipos inicialmente reconhecidos são:
 *
 * COLLECT_DEALS
 * ENRICH_DEAL
 * EVALUATE_DEAL
 *
 * Publicação permanece reservada para fase posterior.
 */
CREATE TABLE processing_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    job_type TEXT NOT NULL,
    status TEXT NOT NULL,

    /*
     * Cada tipo de job aponta para exatamente um tipo de sujeito.
     */
    processing_run_id BIGINT,
    deal_candidate_id BIGINT,
    offer_snapshot_id BIGINT,

    /*
     * Protege a criação repetida do mesmo trabalho lógico.
     */
    idempotency_key TEXT NOT NULL,

    attempt_count INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,

    /*
     * Permite retry com atraso sem bloquear o worker.
     */
    available_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    /*
     * Lease do worker.
     */
    locked_at TIMESTAMPTZ,
    locked_by TEXT,

    /*
     * Classificação da última falha.
     */
    last_failure_type TEXT,
    last_error_code TEXT,
    last_error_message TEXT,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    finished_at TIMESTAMPTZ,

    CONSTRAINT fk_processing_job_run
        FOREIGN KEY (processing_run_id)
        REFERENCES processing_run (id),

    CONSTRAINT fk_processing_job_candidate
        FOREIGN KEY (deal_candidate_id)
        REFERENCES deal_candidate (id),

    CONSTRAINT fk_processing_job_snapshot
        FOREIGN KEY (offer_snapshot_id)
        REFERENCES offer_snapshot (id),

    CONSTRAINT uq_processing_job_idempotency
        UNIQUE (
            job_type,
            idempotency_key
        ),

    CONSTRAINT ck_processing_job_type
        CHECK (
            job_type IN (
                'COLLECT_DEALS',
                'ENRICH_DEAL',
                'EVALUATE_DEAL'
            )
        ),

    CONSTRAINT ck_processing_job_status
        CHECK (
            status IN (
                'PENDING',
                'RUNNING',
                'RETRY_WAIT',
                'SUCCEEDED',
                'DEAD'
            )
        ),

    CONSTRAINT ck_processing_job_failure_type
        CHECK (
            last_failure_type IS NULL
            OR last_failure_type IN (
                'TRANSIENT',
                'PERMANENT'
            )
        ),

    CONSTRAINT ck_processing_job_attempt_count
        CHECK (
            attempt_count >= 0
            AND max_attempts > 0
            AND attempt_count <= max_attempts
        ),

    /*
     * Garante que o sujeito do job corresponda ao tipo da etapa.
     */
    CONSTRAINT ck_processing_job_subject
        CHECK (
            (
                job_type = 'COLLECT_DEALS'
                AND processing_run_id IS NOT NULL
                AND deal_candidate_id IS NULL
                AND offer_snapshot_id IS NULL
            )
            OR
            (
                job_type = 'ENRICH_DEAL'
                AND processing_run_id IS NULL
                AND deal_candidate_id IS NOT NULL
                AND offer_snapshot_id IS NULL
            )
            OR
            (
                job_type = 'EVALUATE_DEAL'
                AND processing_run_id IS NULL
                AND deal_candidate_id IS NULL
                AND offer_snapshot_id IS NOT NULL
            )
        ),

    CONSTRAINT ck_processing_job_running_lock
        CHECK (
            status <> 'RUNNING'
            OR (
                locked_at IS NOT NULL
                AND locked_by IS NOT NULL
                AND CHAR_LENGTH(TRIM(locked_by)) > 0
            )
        )
);


/* ================================================================
 * INDEXES
 * ================================================================ */

CREATE INDEX idx_deal_candidate_processing_run
    ON deal_candidate (
        processing_run_id,
        id
    );


/*
 * Índice principal para claim de jobs.
 *
 * A próxima etapa usará:
 *
 * WHERE status IN ('PENDING', 'RETRY_WAIT')
 *   AND available_at <= ?
 *
 * ORDER BY available_at, id
 *
 * FOR UPDATE SKIP LOCKED
 */
CREATE INDEX idx_processing_job_claim
    ON processing_job (
        status,
        available_at,
        id
    )
    WHERE status IN (
        'PENDING',
        'RETRY_WAIT'
    );


/*
 * Suporte à recuperação de jobs cujo worker deixou de responder.
 */
CREATE INDEX idx_processing_job_running_lease
    ON processing_job (
        locked_at,
        id
    )
    WHERE status = 'RUNNING';


CREATE INDEX idx_processing_job_candidate
    ON processing_job (
        deal_candidate_id
    )
    WHERE deal_candidate_id IS NOT NULL;


CREATE INDEX idx_processing_job_snapshot
    ON processing_job (
        offer_snapshot_id
    )
    WHERE offer_snapshot_id IS NOT NULL;
