CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asin VARCHAR(10) NOT NULL,
    title TEXT NOT NULL,
    image_url TEXT,
    product_url TEXT NOT NULL,

    CONSTRAINT uq_product_asin UNIQUE (asin)
);

CREATE TABLE offer_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    collected_at TIMESTAMPTZ NOT NULL,
    current_price NUMERIC NOT NULL,
    previous_price NUMERIC,
    discount_percentage NUMERIC,
    sold_percentage NUMERIC,
    rating NUMERIC,
    review_count INTEGER,
    seller_name TEXT NOT NULL,
    delivery_provider TEXT NOT NULL,
    source TEXT NOT NULL,

    CONSTRAINT fk_offer_snapshot_product
        FOREIGN KEY (product_id)
        REFERENCES product (id)
);

CREATE TABLE deal_evaluation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_snapshot_id BIGINT NOT NULL,
    eligible BOOLEAN NOT NULL,
    rejection_reason TEXT,
    filter_version TEXT NOT NULL,
    score NUMERIC,
    momentum NUMERIC,
    evaluated_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_deal_evaluation_offer_snapshot
        FOREIGN KEY (offer_snapshot_id)
        REFERENCES offer_snapshot (id)
);

CREATE TABLE publication (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deal_evaluation_id BIGINT NOT NULL,
    template_version TEXT NOT NULL,
    generated_text TEXT NOT NULL,
    affiliate_url TEXT,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_publication_deal_evaluation
        FOREIGN KEY (deal_evaluation_id)
        REFERENCES deal_evaluation (id)
);

CREATE TABLE publication_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publication_id BIGINT NOT NULL,
    channel TEXT NOT NULL,
    target TEXT NOT NULL,
    attempt_number INTEGER NOT NULL,
    status TEXT NOT NULL,
    provider_reference TEXT,
    error_code TEXT,
    created_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_publication_attempt_publication
        FOREIGN KEY (publication_id)
        REFERENCES publication (id)
);

CREATE TABLE configuration_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL,
    value TEXT NOT NULL,
    version INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_offer_snapshot_collected_at
    ON offer_snapshot (collected_at);

CREATE INDEX idx_deal_evaluation_score
    ON deal_evaluation (score);

CREATE INDEX idx_publication_status
    ON publication (status);

CREATE INDEX idx_publication_attempt_status
    ON publication_attempt (status);