/*
 * FASE 18
 *
 * Seleção operacional, recorrência, quota e auditoria de publicação.
 *
 * Esta migration introduz:
 *
 * - perfil temporal versionado de seleção;
 * - perfil versionado de quota;
 * - execução auditável da seleção;
 * - decisão auditável por DealEvaluation;
 * - índice de suporte à leitura do histórico de publicações
 *   externas concluídas com sucesso.
 *
 * A outbox de publicação NÃO pertence a esta migration.
 * Ela possuirá identidade, concorrência e ciclo de vida próprios
 * em migration posterior da FASE 18.
 */


/* ================================================================
 * PUBLICATION SELECTION PROFILE
 * ================================================================ */

/*
 * Configuração temporal utilizada pela política
 * PUBLICATION_SELECTION_V1.
 *
 * O escopo é deliberadamente:
 *
 * channel + destination
 *
 * para permitir futura operação multi-canal sem condicionais
 * específicos de Telegram ou WhatsApp no domínio.
 */
CREATE TABLE publication_selection_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    channel TEXT NOT NULL,

    destination TEXT NOT NULL,

    /*
     * Versão semântica da política/configuração.
     *
     * Exemplo:
     *
     * PUBLICATION_SELECTION_V1
     */
    version TEXT NOT NULL,

    /*
     * Candidato com último sucesso mais recente que este intervalo
     * não participa da seleção.
     */
    hard_cooldown_seconds BIGINT NOT NULL,

    /*
     * Após o hard cooldown e antes deste intervalo o candidato
     * continua elegível, porém com prioridade operacional reduzida.
     */
    preferred_cooldown_seconds BIGINT NOT NULL,

    active BOOLEAN NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_publication_selection_profile_scope_version
        UNIQUE (
            channel,
            destination,
            version
        ),

    CONSTRAINT ck_publication_selection_profile_hard_non_negative
        CHECK (
            hard_cooldown_seconds >= 0
        ),

    CONSTRAINT ck_publication_selection_profile_preferred_valid
        CHECK (
            preferred_cooldown_seconds >= hard_cooldown_seconds
        )
);

/*
 * Existe no máximo um perfil temporal ativo por canal e destino.
 *
 * Perfis históricos permanecem disponíveis para auditoria.
 */
CREATE UNIQUE INDEX uq_publication_selection_profile_single_active_scope
    ON publication_selection_profile (
        channel,
        destination
    )
    WHERE active = true;


/* ================================================================
 * PUBLICATION QUOTA PROFILE
 * ================================================================ */

/*
 * Configuração da capacidade diária de publicação.
 *
 * Quota não representa horário nem frequência de execução.
 * Scheduler continua sendo responsabilidade da FASE 17.
 */
CREATE TABLE publication_quota_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    channel TEXT NOT NULL,

    destination TEXT NOT NULL,

    /*
     * Identidade semântica da configuração de quota.
     *
     * Exemplo:
     *
     * PUBLICATION_QUOTA_V1
     */
    version TEXT NOT NULL,

    max_publications_per_day INTEGER NOT NULL,

    /*
     * ZoneId utilizada para definir a fronteira do dia operacional.
     *
     * Exemplos:
     *
     * America/Sao_Paulo
     * UTC
     *
     * A validação semântica da ZoneId pertence à aplicação Java.
     */
    quota_zone TEXT NOT NULL,

    active BOOLEAN NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_publication_quota_profile_scope_version
        UNIQUE (
            channel,
            destination,
            version
        ),

    CONSTRAINT ck_publication_quota_profile_max_positive
        CHECK (
            max_publications_per_day > 0
        )
);

/*
 * Existe no máximo uma configuração ativa de quota
 * por canal e destino.
 */
CREATE UNIQUE INDEX uq_publication_quota_profile_single_active_scope
    ON publication_quota_profile (
        channel,
        destination
    )
    WHERE active = true;


/* ================================================================
 * PUBLICATION SELECTION RUN
 * ================================================================ */

/*
 * Representa uma execução completa da seleção operacional.
 *
 * Esta linha preserva o contexto utilizado para decidir:
 *
 * - quando;
 * - para qual canal;
 * - para qual destino;
 * - com qual política temporal;
 * - com qual snapshot de quota.
 *
 * SELECTED neste estágio ainda não significa quota definitivamente
 * reservada. A reserva definitiva ocorrerá no enqueue da outbox.
 */
CREATE TABLE publication_selection_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    channel TEXT NOT NULL,

    destination TEXT NOT NULL,

    decided_at TIMESTAMPTZ NOT NULL,

    /*
     * Perfil temporal efetivamente utilizado.
     */
    selection_profile_version TEXT NOT NULL,

    /*
     * Os valores são copiados para a execução para preservar
     * exatamente a configuração observada no momento da decisão.
     */
    hard_cooldown_seconds BIGINT NOT NULL,

    preferred_cooldown_seconds BIGINT NOT NULL,

    /*
     * Perfil de quota observado.
     */
    quota_profile_version TEXT NOT NULL,

    quota_date DATE NOT NULL,

    max_publications_per_day INTEGER NOT NULL,

    /*
     * Quantidade de posições já ocupadas no snapshot consultado
     * antes desta seleção.
     *
     * Pode ser superior a max_publications_per_day caso a
     * configuração tenha sido reduzida durante o mesmo dia.
     */
    occupied_slots BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_publication_selection_run_selection_profile
        FOREIGN KEY (
            channel,
            destination,
            selection_profile_version
        )
        REFERENCES publication_selection_profile (
            channel,
            destination,
            version
        ),

    CONSTRAINT fk_publication_selection_run_quota_profile
        FOREIGN KEY (
            channel,
            destination,
            quota_profile_version
        )
        REFERENCES publication_quota_profile (
            channel,
            destination,
            version
        ),

    CONSTRAINT ck_publication_selection_run_hard_non_negative
        CHECK (
            hard_cooldown_seconds >= 0
        ),

    CONSTRAINT ck_publication_selection_run_preferred_valid
        CHECK (
            preferred_cooldown_seconds >= hard_cooldown_seconds
        ),

    CONSTRAINT ck_publication_selection_run_max_positive
        CHECK (
            max_publications_per_day > 0
        ),

    CONSTRAINT ck_publication_selection_run_occupied_non_negative
        CHECK (
            occupied_slots >= 0
        )
);


/* ================================================================
 * PUBLICATION SELECTION DECISION
 * ================================================================ */

/*
 * Preserva a decisão tomada para cada candidato analisado.
 *
 * O registro mantém deliberadamente alguns fatos já existentes em
 * outras tabelas, como ASIN e score.
 *
 * Isto é intencional:
 *
 * a auditoria deve explicar o que a política efetivamente observou
 * naquele instante, e não reconstruir silenciosamente a decisão a
 * partir do estado atual de outras tabelas.
 */
CREATE TABLE publication_selection_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    selection_run_id BIGINT NOT NULL,

    deal_evaluation_id BIGINT NOT NULL,

    asin TEXT NOT NULL,

    score NUMERIC NOT NULL,

    /*
     * Resultado operacional da seleção:
     *
     * SELECTED
     * DEFERRED_DUE_TO_HARD_COOLDOWN
     * NOT_SELECTED_DUE_TO_QUOTA
     */
    decision_status TEXT NOT NULL,

    /*
     * Situação temporal observada:
     *
     * NEVER_SUCCESSFULLY_PUBLISHED
     * OUTSIDE_PREFERRED_COOLDOWN
     * INSIDE_PREFERRED_COOLDOWN
     * INSIDE_HARD_COOLDOWN
     */
    recency TEXT NOT NULL,

    /*
     * Posição 1-based entre candidatos elegíveis.
     *
     * NULL somente para candidato dentro do hard cooldown,
     * pois ele não participou da ordenação do ciclo.
     */
    priority_position INTEGER,

    /*
     * Histórico de sucesso observado durante a decisão.
     *
     * Nunca publicado:
     *
     * last_successful_publication_at = NULL
     * successful_publication_count = 0
     *
     * Já publicado:
     *
     * last_successful_publication_at != NULL
     * successful_publication_count > 0
     */
    last_successful_publication_at TIMESTAMPTZ,

    successful_publication_count BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_publication_selection_decision_run
        FOREIGN KEY (
            selection_run_id
        )
        REFERENCES publication_selection_run (
            id
        )
        ON DELETE CASCADE,

    CONSTRAINT fk_publication_selection_decision_evaluation
        FOREIGN KEY (
            deal_evaluation_id
        )
        REFERENCES deal_evaluation (
            id
        )
        ON DELETE CASCADE,

    /*
     * Uma DealEvaluation pode aparecer apenas uma vez em uma
     * determinada execução.
     */
    CONSTRAINT uq_publication_selection_decision_run_evaluation
        UNIQUE (
            selection_run_id,
            deal_evaluation_id
        ),

    /*
     * PostgreSQL permite múltiplos NULL em UNIQUE.
     *
     * Portanto:
     *
     * candidatos elegíveis possuem posições únicas;
     * candidatos em hard cooldown podem compartilhar NULL.
     */
    CONSTRAINT uq_publication_selection_decision_run_position
        UNIQUE (
            selection_run_id,
            priority_position
        ),

    CONSTRAINT ck_publication_selection_decision_status
        CHECK (
            decision_status IN (
                'SELECTED',
                'DEFERRED_DUE_TO_HARD_COOLDOWN',
                'NOT_SELECTED_DUE_TO_QUOTA'
            )
        ),

    CONSTRAINT ck_publication_selection_decision_recency
        CHECK (
            recency IN (
                'NEVER_SUCCESSFULLY_PUBLISHED',
                'OUTSIDE_PREFERRED_COOLDOWN',
                'INSIDE_PREFERRED_COOLDOWN',
                'INSIDE_HARD_COOLDOWN'
            )
        ),

    CONSTRAINT ck_publication_selection_decision_position_positive
        CHECK (
            priority_position IS NULL
            OR priority_position > 0
        ),

    CONSTRAINT ck_publication_selection_decision_history
        CHECK (
            (
                recency = 'NEVER_SUCCESSFULLY_PUBLISHED'
                AND last_successful_publication_at IS NULL
                AND successful_publication_count = 0
            )
            OR
            (
                recency <> 'NEVER_SUCCESSFULLY_PUBLISHED'
                AND last_successful_publication_at IS NOT NULL
                AND successful_publication_count > 0
            )
        ),

    /*
     * Hard cooldown:
     *
     * - obrigatoriamente deferred;
     * - sem posição operacional.
     *
     * Todos os demais:
     *
     * - SELECTED ou quota;
     * - posição obrigatória.
     */
    CONSTRAINT ck_publication_selection_decision_status_recency_position
        CHECK (
            (
                recency = 'INSIDE_HARD_COOLDOWN'
                AND decision_status =
                    'DEFERRED_DUE_TO_HARD_COOLDOWN'
                AND priority_position IS NULL
            )
            OR
            (
                recency <> 'INSIDE_HARD_COOLDOWN'
                AND decision_status IN (
                    'SELECTED',
                    'NOT_SELECTED_DUE_TO_QUOTA'
                )
                AND priority_position IS NOT NULL
            )
        )
);


/* ================================================================
 * AUDIT READ INDEXES
 * ================================================================ */

/*
 * Histórico de execuções por escopo operacional.
 */
CREATE INDEX idx_publication_selection_run_scope_decided
    ON publication_selection_run (
        channel,
        destination,
        decided_at DESC,
        id DESC
    );

/*
 * Consulta de decisões de uma execução por resultado.
 */
CREATE INDEX idx_publication_selection_decision_run_status
    ON publication_selection_decision (
        selection_run_id,
        decision_status
    );

/*
 * Histórico de seleções associadas a uma DealEvaluation.
 */
CREATE INDEX idx_publication_selection_decision_evaluation_run
    ON publication_selection_decision (
        deal_evaluation_id,
        selection_run_id DESC
    );


/* ================================================================
 * SUCCESSFUL PUBLICATION HISTORY READ INDEX
 * ================================================================ */

/*
 * Suporte à consulta introduzida na FASE 18.1.
 *
 * A recorrência considera exclusivamente tentativas externas
 * concluídas com SUCCESS e sempre dentro do escopo:
 *
 * channel + target
 *
 * publication_id permite seguir a cadeia:
 *
 * publication_attempt
 *     -> publication
 *     -> deal_evaluation
 *     -> offer_snapshot
 *     -> product
 */
CREATE INDEX idx_publication_attempt_success_scope
    ON publication_attempt (
        channel,
        target,
        publication_id,
        created_at DESC
    )
    WHERE status = 'SUCCESS';
