/*
 * FASE 18
 *
 * Outbox persistente de publicação.
 *
 * Esta migration introduz a unidade durável de trabalho que será
 * entregue posteriormente por PublicationChannel.
 *
 * Responsabilidades da tabela:
 *
 * - preservar a identidade da publicação selecionada;
 * - preservar channel + destination;
 * - preservar o conteúdo final que será enviado;
 * - preservar a posição da seleção que originou o trabalho;
 * - representar a reserva persistente da quota;
 * - permitir claim concorrente posterior pelo worker;
 * - impedir duplicação simples de envio para o mesmo destino.
 *
 * Esta migration NÃO implementa:
 *
 * - Telegram;
 * - WhatsApp;
 * - worker;
 * - retry automático;
 * - backoff;
 * - rate limit;
 * - PublicationAttempt detalhado da FASE 19.
 */


/* ================================================================
 * PUBLICATION OUTBOX
 * ================================================================ */

CREATE TABLE publication_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /*
     * Publication efetivamente aprovada para entrega.
     *
     * O enqueue da FASE 18 exigirá Publication.status = READY.
     */
    publication_id BIGINT NOT NULL,

    /*
     * Execução auditável da política que selecionou esta publicação.
     *
     * A outbox não recalcula ranking, score, histórico ou cooldown.
     */
    selection_run_id BIGINT NOT NULL,

    /*
     * Posição 1-based produzida pela PublicationSelectionPolicy.
     *
     * Esta posição preserva a ordem do trabalho selecionado.
     *
     * Ela vale somente para a seleção que originou esta linha.
     * Não concede prioridade em ciclos futuros.
     */
    selection_position INTEGER NOT NULL,

    /*
     * Escopo operacional da entrega.
     */
    channel TEXT NOT NULL,

    destination TEXT NOT NULL,

    /*
     * Conteúdo já completamente preparado para PublicationChannel.
     *
     * O worker não deverá consultar OfferSnapshot, DealEvaluation
     * ou outros repositories para construir a mensagem.
     */
    content TEXT NOT NULL,

    /*
     * Configuração de quota sob a qual a vaga foi reservada.
     */
    quota_profile_version TEXT NOT NULL,

    /*
     * Dia operacional em que esta linha ocupa quota.
     *
     * A fronteira do dia é determinada pela ZoneId do
     * publication_quota_profile durante o enqueue.
     */
    quota_date DATE NOT NULL,

    /*
     * Estados da outbox na FASE 18:
     *
     * PENDING
     *     trabalho reservado aguardando worker.
     *
     * PROCESSING
     *     trabalho atualmente reivindicado por um worker.
     *
     * SUCCEEDED
     *     canal devolveu SUCCESS.
     *
     * FAILED_TRANSIENT
     *     canal devolveu falha transitória.
     *     A política real de retry será refinada na FASE 19.
     *
     * FAILED_PERMANENT
     *     canal devolveu falha permanente.
     */
    status TEXT NOT NULL DEFAULT 'PENDING',

    /*
     * Permite que a publicação fique reservada agora e somente seja
     * elegível para claim quando sua janela operacional chegar.
     */
    available_at TIMESTAMPTZ NOT NULL,

    /*
     * Lease técnico do worker.
     */
    locked_at TIMESTAMPTZ,

    locked_by TEXT,

    /*
     * created_at representa também o instante persistente em que
     * a quota foi reservada.
     */
    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    /*
     * Última conclusão da execução desta entrada.
     *
     * Na FASE 18, SUCCESS e ambas as classificações de falha
     * finalizam a tentativa corrente.
     *
     * Uma estratégia futura de retry poderá reabrir uma falha
     * transitória e limpar finished_at dentro de uma transação.
     */
    finished_at TIMESTAMPTZ,

    CONSTRAINT fk_publication_outbox_publication
        FOREIGN KEY (
            publication_id
        )
        REFERENCES publication (
            id
        ),

    CONSTRAINT fk_publication_outbox_selection_run
        FOREIGN KEY (
            selection_run_id
        )
        REFERENCES publication_selection_run (
            id
        ),

    /*
     * Garante que a versão de quota registrada realmente exista
     * para o mesmo canal e destino.
     *
     * V25 já fornece:
     *
     * UNIQUE (channel, destination, version)
     */
    CONSTRAINT fk_publication_outbox_quota_profile
        FOREIGN KEY (
            channel,
            destination,
            quota_profile_version
        )
        REFERENCES publication_quota_profile (
            channel,
            destination,
            version
        ),

    /*
     * Idempotência mínima definida pela FASE 18:
     *
     * publication + channel + destination
     *
     * Reiniciar worker ou repetir enqueue não cria uma segunda
     * entrega lógica.
     */
    CONSTRAINT uq_publication_outbox_delivery_identity
        UNIQUE (
            publication_id,
            channel,
            destination
        ),

    /*
     * Uma posição selecionada dentro de uma execução pode originar
     * no máximo uma entrada de outbox.
     *
     * Nem toda posição SELECTED precisa necessariamente chegar aqui:
     * quota poderá ter sido consumida concorrentemente entre
     * seleção e enqueue.
     */
    CONSTRAINT uq_publication_outbox_selection_position
        UNIQUE (
            selection_run_id,
            selection_position
        ),

    CONSTRAINT ck_publication_outbox_selection_position
        CHECK (
            selection_position > 0
        ),

    CONSTRAINT ck_publication_outbox_channel
        CHECK (
            CHAR_LENGTH(TRIM(channel)) > 0
        ),

    CONSTRAINT ck_publication_outbox_destination
        CHECK (
            CHAR_LENGTH(TRIM(destination)) > 0
        ),

    CONSTRAINT ck_publication_outbox_content
        CHECK (
            CHAR_LENGTH(TRIM(content)) > 0
        ),

    CONSTRAINT ck_publication_outbox_quota_profile_version
        CHECK (
            CHAR_LENGTH(TRIM(quota_profile_version)) > 0
        ),

    CONSTRAINT ck_publication_outbox_status
        CHECK (
            status IN (
                'PENDING',
                'PROCESSING',
                'SUCCEEDED',
                'FAILED_TRANSIENT',
                'FAILED_PERMANENT'
            )
        ),

    /*
     * Somente PROCESSING possui lease.
     */
    CONSTRAINT ck_publication_outbox_lock_state
        CHECK (
            (
                status = 'PROCESSING'
                AND locked_at IS NOT NULL
                AND locked_by IS NOT NULL
                AND CHAR_LENGTH(TRIM(locked_by)) > 0
                AND finished_at IS NULL
            )
            OR
            (
                status <> 'PROCESSING'
                AND locked_at IS NULL
                AND locked_by IS NULL
            )
        ),

    /*
     * PENDING ainda não terminou.
     *
     * PROCESSING também não terminou.
     *
     * Os três resultados produzidos pelo canal encerram a tentativa
     * corrente e exigem finished_at.
     */
    CONSTRAINT ck_publication_outbox_finished_state
        CHECK (
            (
                status IN (
                    'PENDING',
                    'PROCESSING'
                )
                AND finished_at IS NULL
            )
            OR
            (
                status IN (
                    'SUCCEEDED',
                    'FAILED_TRANSIENT',
                    'FAILED_PERMANENT'
                )
                AND finished_at IS NOT NULL
            )
        )
);


/* ================================================================
 * QUOTA
 * ================================================================ */

/*
 * A existência da linha representa uma vaga já reservada.
 *
 * Portanto a futura consulta da quota contará:
 *
 * channel
 * +
 * destination
 * +
 * quota_date
 *
 * independentemente do status atual.
 *
 * Isso é intencional.
 *
 * Retry do mesmo trabalho continuará ocupando a mesma vaga.
 * Falha não cria automaticamente uma nova vaga para outro candidato.
 *
 * Candidatos que não conseguiram reserva NÃO ganham linha de outbox
 * e deverão passar por uma nova seleção futura.
 */
CREATE INDEX idx_publication_outbox_quota_scope
    ON publication_outbox (
        channel,
        destination,
        quota_date,
        id
    );


/* ================================================================
 * CLAIM
 * ================================================================ */

/*
 * Índice da futura operação:
 *
 * WHERE status = 'PENDING'
 *   AND available_at <= ?
 *
 * ORDER BY
 *     available_at,
 *     selection_run_id,
 *     selection_position,
 *     id
 *
 * FOR UPDATE SKIP LOCKED
 */
CREATE INDEX idx_publication_outbox_claim
    ON publication_outbox (
        available_at,
        selection_run_id,
        selection_position,
        id
    )
    WHERE status = 'PENDING';


/* ================================================================
 * LEASE RECOVERY
 * ================================================================ */

/*
 * Suporte à futura recuperação de trabalho PROCESSING cujo worker
 * deixou de responder.
 */
CREATE INDEX idx_publication_outbox_processing_lease
    ON publication_outbox (
        locked_at,
        id
    )
    WHERE status = 'PROCESSING';


/* ================================================================
 * SELECTION AUDIT NAVIGATION
 * ================================================================ */

/*
 * Permite navegar da execução auditada para as reservas que
 * efetivamente chegaram à outbox.
 */
CREATE INDEX idx_publication_outbox_selection_run
    ON publication_outbox (
        selection_run_id,
        selection_position,
        id
    );
