/*
 * FASE 19
 *
 * Perfil versionado de cadência de publicação.
 *
 * Quota e cadência permanecem conceitos independentes:
 *
 * quota
 *     = capacidade máxima dentro do dia operacional
 *
 * cadência
 *     = intervalo e janela nos quais entregas podem
 *       ser disponibilizadas
 *
 * Perfis históricos nunca são alterados ou reativados.
 */

CREATE TABLE publication_cadence_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    channel TEXT NOT NULL,

    destination TEXT NOT NULL,

    /*
     * Identidade semântica da configuração.
     *
     * Exemplos:
     *
     * CADENCE_V1
     * CADENCE_V2
     */
    version TEXT NOT NULL,

    /*
     * Intervalo entre slots de publicação.
     *
     * Persistimos segundos para evitar dependência de uma
     * representação textual específica de Duration.
     */
    interval_seconds BIGINT NOT NULL,

    /*
     * Janela operacional local.
     *
     * window_end < window_start representa janela que atravessa
     * a meia-noite.
     *
     * Exemplo:
     *
     * 22:00 -> 02:00
     */
    window_start TIME NOT NULL,

    window_end TIME NOT NULL,

    /*
     * ZoneId utilizada para interpretar a janela operacional.
     *
     * Exemplo:
     *
     * America/Sao_Paulo
     */
    cadence_zone TEXT NOT NULL,

    active BOOLEAN NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_publication_cadence_profile_scope_version
        UNIQUE (
            channel,
            destination,
            version
        ),

    CONSTRAINT ck_publication_cadence_profile_interval_positive
        CHECK (
            interval_seconds > 0
        ),

    CONSTRAINT ck_publication_cadence_profile_window_distinct
        CHECK (
            window_start <> window_end
        )
);

/*
 * No máximo uma política de cadência ativa por
 * channel + destination.
 *
 * As demais permanecem como histórico.
 */
CREATE UNIQUE INDEX
    uq_publication_cadence_profile_single_active_scope
    ON publication_cadence_profile (
        channel,
        destination
    )
    WHERE active = true;

COMMENT ON TABLE publication_cadence_profile IS
    'Versioned publication cadence configuration by channel and destination';

COMMENT ON COLUMN publication_cadence_profile.active IS
    'Only the current cadence version is active; historical versions remain immutable';
