/*
 * FASE 20-F
 *
 * Auditoria idempotente do reprocessamento manual de ProcessingJob.
 *
 * O próprio processing_job em status DEAD funciona como dead-letter
 * lógico. Esta tabela registra a decisão operacional que autoriza
 * reabrir a mesma identidade de job.
 *
 * A migration NÃO altera:
 *
 * - a unique key (job_type, idempotency_key);
 * - os estados existentes de processing_job;
 * - a política automática de retry;
 * - publication_outbox.
 */

CREATE TABLE processing_job_reprocess_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    processing_job_id BIGINT NOT NULL,

    /*
     * Identidade idempotente fornecida pela camada operacional.
     *
     * Uma repetição da mesma decisão deve encontrar o evento já
     * aplicado em vez de reabrir o job novamente.
     */
    request_key TEXT NOT NULL,

    requested_by TEXT NOT NULL,

    reason TEXT NOT NULL,

    requested_at TIMESTAMPTZ NOT NULL,

    /*
     * Fotografia do estado terminal que motivou o reprocessamento.
     *
     * Esses campos preservam a evidência mesmo depois que o
     * processing_job voltar a PENDING e limpar sua falha corrente.
     */
    previous_status TEXT NOT NULL,
    previous_attempt_count INTEGER NOT NULL,
    previous_max_attempts INTEGER NOT NULL,
    previous_failure_type TEXT,
    previous_error_code TEXT,
    previous_error_message TEXT,
    previous_finished_at TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_processing_job_reprocess_event_job
        FOREIGN KEY (processing_job_id)
        REFERENCES processing_job (id),

    CONSTRAINT uq_processing_job_reprocess_event_request_key
        UNIQUE (request_key),

    CONSTRAINT ck_processing_job_reprocess_event_request_key
        CHECK (
            CHAR_LENGTH(TRIM(request_key)) > 0
        ),

    CONSTRAINT ck_processing_job_reprocess_event_requested_by
        CHECK (
            CHAR_LENGTH(TRIM(requested_by)) > 0
        ),

    CONSTRAINT ck_processing_job_reprocess_event_reason
        CHECK (
            CHAR_LENGTH(TRIM(reason)) > 0
        ),

    CONSTRAINT ck_processing_job_reprocess_event_previous_status
        CHECK (
            previous_status = 'DEAD'
        ),

    CONSTRAINT ck_processing_job_reprocess_event_attempts
        CHECK (
            previous_attempt_count >= 0
            AND previous_max_attempts > 0
            AND previous_attempt_count <= previous_max_attempts
        ),

    CONSTRAINT ck_processing_job_reprocess_event_failure_type
        CHECK (
            previous_failure_type IS NULL
            OR previous_failure_type IN (
                'TRANSIENT',
                'PERMANENT'
            )
        )
);

CREATE INDEX idx_processing_job_reprocess_event_job
    ON processing_job_reprocess_event (
        processing_job_id,
        requested_at DESC,
        id DESC
    );
