/*
 * FASE 20-F2
 *
 * Auditoria de decisões operacionais sobre publication_outbox em
 * DELIVERY_UNKNOWN.
 *
 * A tentativa original permanece DELIVERY_UNKNOWN. Esta tabela
 * registra conhecimento posterior sem reescrever retroativamente o
 * que o worker sabia quando executou a chamada externa.
 *
 * Nenhuma coluna de publication_attempt é alterada.
 * Nenhuma decisão é aplicada automaticamente por esta migration.
 */

CREATE TABLE publication_delivery_resolution_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    publication_outbox_id BIGINT NOT NULL,

    /*
     * Identidade idempotente da decisão operacional.
     */
    request_key TEXT NOT NULL,

    decision TEXT NOT NULL,

    /*
     * Estado que a decisão produz quando efetivamente aplicada.
     *
     * CONFIRMED_DELIVERED
     *     -> SUCCEEDED
     *
     * CONFIRMED_NOT_DELIVERED
     *     -> PENDING
     *
     * REMAINS_UNKNOWN
     *     -> DELIVERY_UNKNOWN
     */
    resulting_status TEXT NOT NULL,

    decided_by TEXT NOT NULL,

    /*
     * Evidência textual que fundamenta a decisão.
     *
     * Exemplos:
     * - referência consultada no provedor;
     * - verificação operacional no destino;
     * - resposta de suporte;
     * - evidência de que a requisição não foi aceita.
     */
    evidence TEXT NOT NULL,

    /*
     * Referência do provedor quando estiver disponível.
     *
     * Ela é deliberadamente opcional: uma confirmação operacional
     * pode existir sem identificador retornado pelo provider.
     */
    provider_reference TEXT,

    resolved_at TIMESTAMPTZ NOT NULL,

    /*
     * Snapshot do estado ambíguo anterior.
     */
    previous_status TEXT NOT NULL,
    previous_finished_at TIMESTAMPTZ NOT NULL,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_publication_delivery_resolution_outbox
        FOREIGN KEY (
            publication_outbox_id
        )
        REFERENCES publication_outbox (
            id
        ),

    CONSTRAINT uq_publication_delivery_resolution_request_key
        UNIQUE (
            request_key
        ),

    CONSTRAINT ck_publication_delivery_resolution_request_key
        CHECK (
            CHAR_LENGTH(TRIM(request_key)) > 0
        ),

    CONSTRAINT ck_publication_delivery_resolution_decision
        CHECK (
            decision IN (
                'CONFIRMED_DELIVERED',
                'CONFIRMED_NOT_DELIVERED',
                'REMAINS_UNKNOWN'
            )
        ),

    CONSTRAINT ck_publication_delivery_resolution_result
        CHECK (
            (
                decision = 'CONFIRMED_DELIVERED'
                AND resulting_status = 'SUCCEEDED'
            )
            OR
            (
                decision = 'CONFIRMED_NOT_DELIVERED'
                AND resulting_status = 'PENDING'
            )
            OR
            (
                decision = 'REMAINS_UNKNOWN'
                AND resulting_status = 'DELIVERY_UNKNOWN'
            )
        ),

    CONSTRAINT ck_publication_delivery_resolution_decided_by
        CHECK (
            CHAR_LENGTH(TRIM(decided_by)) > 0
        ),

    CONSTRAINT ck_publication_delivery_resolution_evidence
        CHECK (
            CHAR_LENGTH(TRIM(evidence)) > 0
        ),

    CONSTRAINT ck_publication_delivery_resolution_provider_reference
        CHECK (
            provider_reference IS NULL
            OR CHAR_LENGTH(TRIM(provider_reference)) > 0
        ),

    CONSTRAINT ck_publication_delivery_resolution_previous_status
        CHECK (
            previous_status = 'DELIVERY_UNKNOWN'
        )
);

CREATE INDEX idx_publication_delivery_resolution_outbox
    ON publication_delivery_resolution_event (
        publication_outbox_id,
        resolved_at DESC,
        id DESC
    );
