CREATE TABLE offer_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /*
     * Snapshot ao qual esta evidência pertence.
     *
     * Uma mesma fotografia de oferta poderá ter várias evidências
     * no futuro. Nesta fase teremos SELLER e DELIVERY.
     */
    offer_snapshot_id BIGINT NOT NULL,

    /*
     * Tipo semântico da evidência.
     *
     * Valores iniciais utilizados pela aplicação:
     *
     * SELLER
     * DELIVERY
     *
     * Mantemos TEXT em vez de CHECK rígido porque novos tipos
     * de evidência podem surgir em fases futuras sem exigir
     * alteração imediata da estrutura da tabela.
     */
    evidence_type TEXT NOT NULL,

    /*
     * Texto observado diretamente na fonte.
     *
     * Pode ser NULL quando a informação não foi encontrada.
     * Isso é importante porque ausência de evidência também é
     * informação auditável.
     */
    raw_value TEXT,

    /*
     * Valor normalizado utilizado pelas regras da aplicação.
     *
     * Exemplos:
     *
     * AMAZON
     * THIRD_PARTY
     * UNKNOWN
     */
    normalized_value TEXT NOT NULL,

    /*
     * Adaptador geral responsável pela obtenção da informação.
     *
     * Exemplo:
     * AMAZON_PRODUCT_PAGE
     */
    source_adapter TEXT NOT NULL,

    /*
     * Estrutura/componente específico dentro da fonte que forneceu
     * a evidência.
     *
     * Exemplos:
     * merchantInfoFeature
     * fulfillerInfoFeature
     *
     * Pode ser NULL quando nenhuma estrutura confiável foi encontrada.
     */
    source_component TEXT,

    /*
     * Momento em que esta evidência foi observada.
     *
     * Não é necessariamente o mesmo collected_at do snapshot.
     * O snapshot representa a coleta comercial; este timestamp
     * representa especificamente o enriquecimento.
     */
    observed_at TIMESTAMPTZ NOT NULL,

    CONSTRAINT fk_offer_evidence_snapshot
        FOREIGN KEY (offer_snapshot_id)
        REFERENCES offer_snapshot (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_offer_evidence_snapshot
    ON offer_evidence (offer_snapshot_id);

CREATE INDEX idx_offer_evidence_type
    ON offer_evidence (evidence_type);