/*
 * FASE 9-C1
 *
 * Introduz a configuração persistida e versionada dos filtros
 * comerciais.
 *
 * Um FilterProfile representa uma unidade atômica de configuração:
 *
 * - desconto mínimo à vista;
 * - rating mínimo;
 * - quantidade mínima de avaliações.
 *
 * soldPercentage não pertence ao perfil, pois foi reservado para
 * score na FASE 10.
 *
 * Seller e delivery também não pertencem ao perfil, pois continuam
 * sob a política estrutural de elegibilidade Amazon.
 */

CREATE TABLE filter_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /*
     * Identidade semântica e estável do perfil.
     *
     * Esta versão será armazenada futuramente em:
     *
     * deal_evaluation.filter_profile_version
     */
    version TEXT NOT NULL,

    /*
     * Percentual mínimo de desconto à vista.
     *
     * O valor representa percentual entre 0 e 100.
     */
    min_cash_discount_percentage NUMERIC(5, 2) NOT NULL,

    /*
     * Rating mínimo agregado do produto.
     *
     * O contrato do domínio trabalha no intervalo de 0 a 5.
     */
    min_rating NUMERIC(3, 2) NOT NULL,

    /*
     * Quantidade mínima de avaliações.
     */
    min_review_count BIGINT NOT NULL,

    /*
     * Somente um perfil pode estar ativo por vez.
     */
    active BOOLEAN NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_filter_profile_version
        UNIQUE (version),

    CONSTRAINT ck_filter_profile_cash_discount_range
        CHECK (
            min_cash_discount_percentage >= 0
            AND min_cash_discount_percentage <= 100
        ),

    CONSTRAINT ck_filter_profile_rating_range
        CHECK (
            min_rating >= 0
            AND min_rating <= 5
        ),

    CONSTRAINT ck_filter_profile_review_count_non_negative
        CHECK (
            min_review_count >= 0
        )
);

/*
 * PostgreSQL permite índice único parcial.
 *
 * Como o índice considera somente linhas active = true,
 * ele garante no máximo um perfil ativo sem impedir a existência
 * de qualquer quantidade de perfis históricos inativos.
 */
CREATE UNIQUE INDEX uq_filter_profile_single_active
    ON filter_profile (active)
    WHERE active = true;

/*
 * Perfil inicial da FASE 9.
 *
 * Estes valores correspondem à primeira configuração comercial
 * formalmente versionada.
 *
 * Alterações futuras não deverão modificar esta linha.
 * Uma mudança de regra deve criar COMMERCIAL_FILTER_V2,
 * COMMERCIAL_FILTER_V3 etc.
 */
INSERT INTO filter_profile (
    version,
    min_cash_discount_percentage,
    min_rating,
    min_review_count,
    active
)
VALUES (
    'COMMERCIAL_FILTER_V1',
    20.00,
    4.30,
    100,
    true
);
