/*
 * FASE 10-E
 *
 * Introduz:
 *
 * 1. configuração persistida e versionada do score;
 * 2. persistência dos fatores individuais que explicam
 *    o score de uma DealEvaluation.
 *
 * deal_evaluation continua armazenando:
 *
 * - score agregado;
 * - score_version.
 *
 * deal_evaluation_score_factor armazena a decomposição auditável
 * que permite reproduzir e explicar esse score.
 */


/* ================================================================
 * SCORE PROFILE
 * ================================================================ */

CREATE TABLE score_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /*
     * Identidade semântica e estável da configuração.
     *
     * Esta versão é armazenada em:
     *
     * deal_evaluation.score_version
     */
    version TEXT NOT NULL,

    /*
     * Pesos dos fatores ativos.
     *
     * Os valores representam pontos máximos de contribuição.
     * Cada peso deve permanecer entre 0 e 100.
     */
    sold_percentage_weight NUMERIC(7, 4) NOT NULL,
    cash_discount_weight NUMERIC(7, 4) NOT NULL,
    rating_weight NUMERIC(7, 4) NOT NULL,
    review_count_weight NUMERIC(7, 4) NOT NULL,

    /*
     * Quantidade de avaliações a partir da qual REVIEW_COUNT
     * atinge normalização igual a 100.
     */
    review_count_full_score_threshold BIGINT NOT NULL,

    /*
     * Somente um ScoreProfile pode estar ativo por vez.
     */
    active BOOLEAN NOT NULL,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_score_profile_version
        UNIQUE (version),

    CONSTRAINT ck_score_profile_sold_percentage_weight_range
        CHECK (
            sold_percentage_weight >= 0
            AND sold_percentage_weight <= 100
        ),

    CONSTRAINT ck_score_profile_cash_discount_weight_range
        CHECK (
            cash_discount_weight >= 0
            AND cash_discount_weight <= 100
        ),

    CONSTRAINT ck_score_profile_rating_weight_range
        CHECK (
            rating_weight >= 0
            AND rating_weight <= 100
        ),

    CONSTRAINT ck_score_profile_review_count_weight_range
        CHECK (
            review_count_weight >= 0
            AND review_count_weight <= 100
        ),

    /*
     * O domínio permite versões futuras cuja soma de pesos seja
     * inferior ou igual a 100.
     *
     * SCORE_V1 soma 90 porque os 10 pontos originalmente reservados
     * à atratividade de preço não são redistribuídos.
     */
    CONSTRAINT ck_score_profile_total_weight
        CHECK (
            sold_percentage_weight
            + cash_discount_weight
            + rating_weight
            + review_count_weight
            <= 100
        ),

    CONSTRAINT ck_score_profile_review_count_threshold_positive
        CHECK (
            review_count_full_score_threshold > 0
        )
);

/*
 * PostgreSQL permite índice único parcial.
 *
 * Isso garante estruturalmente no máximo um perfil ativo,
 * preservando qualquer quantidade de versões históricas inativas.
 */
CREATE UNIQUE INDEX uq_score_profile_single_active
    ON score_profile (active)
    WHERE active = true;


/* ================================================================
 * SCORE_V1
 * ================================================================ */

/*
 * Primeira configuração operacional da FASE 10.
 *
 * Pesos definidos pela ADR-0002:
 *
 * SOLD_PERCENTAGE = 30
 * CASH_DISCOUNT   = 25
 * RATING          = 20
 * REVIEW_COUNT    = 15
 *
 * Soma ativa = 90.
 *
 * review_count_full_score_threshold = 1000
 *
 * Essa linha representa configuração histórica imutável.
 * Mudanças futuras devem criar SCORE_V2, SCORE_V3 etc.
 */
INSERT INTO score_profile (
    version,
    sold_percentage_weight,
    cash_discount_weight,
    rating_weight,
    review_count_weight,
    review_count_full_score_threshold,
    active
)
VALUES (
    'SCORE_V1',
    30.0000,
    25.0000,
    20.0000,
    15.0000,
    1000,
    true
);


/* ================================================================
 * SCORE FACTORS
 * ================================================================ */

CREATE TABLE deal_evaluation_score_factor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /*
     * Avaliação agregada à qual este fator pertence.
     */
    deal_evaluation_id BIGINT NOT NULL,

    /*
     * Ordem determinística dos fatores dentro da avaliação.
     *
     * SCORE_V1:
     *
     * 0 = SOLD_PERCENTAGE
     * 1 = CASH_DISCOUNT
     * 2 = RATING
     * 3 = REVIEW_COUNT
     */
    factor_order INTEGER NOT NULL,

    /*
     * Código semântico estável do fator.
     *
     * Exemplos:
     *
     * SOLD_PERCENTAGE
     * CASH_DISCOUNT
     * RATING
     * REVIEW_COUNT
     */
    factor_code TEXT NOT NULL,

    /*
     * Estado de disponibilidade da evidência.
     *
     * AVAILABLE
     * UNAVAILABLE
     */
    status TEXT NOT NULL,

    /*
     * Valor bruto observado antes da normalização.
     *
     * Exemplos:
     *
     * rating      -> 4.5
     * reviewCount -> 500
     *
     * Deve ser NULL quando status = UNAVAILABLE.
     *
     * NUMERIC sem precisão fixa é intencional porque fatores
     * diferentes possuem escalas brutas diferentes.
     */
    raw_value NUMERIC,

    /*
     * Valor convertido para a escala 0..100.
     *
     * Deve ser NULL quando status = UNAVAILABLE.
     */
    normalized_value NUMERIC(7, 4),

    /*
     * Peso utilizado naquela avaliação.
     *
     * O peso é persistido junto ao resultado para que avaliações
     * históricas continuem auditáveis sem depender somente do
     * ScoreProfile atualmente ativo.
     */
    weight NUMERIC(7, 4) NOT NULL,

    /*
     * Parcela efetivamente adicionada ao score agregado.
     */
    contribution NUMERIC(7, 4) NOT NULL,

    CONSTRAINT fk_deal_evaluation_score_factor_evaluation
        FOREIGN KEY (deal_evaluation_id)
        REFERENCES deal_evaluation (id)
        ON DELETE CASCADE,

    /*
     * Uma avaliação não pode possuir dois fatores na mesma posição.
     */
    CONSTRAINT uq_deal_evaluation_score_factor_order
        UNIQUE (deal_evaluation_id, factor_order),

    /*
     * Um mesmo código de fator aparece no máximo uma vez
     * por avaliação.
     */
    CONSTRAINT uq_deal_evaluation_score_factor_code
        UNIQUE (deal_evaluation_id, factor_code),

    CONSTRAINT ck_deal_evaluation_score_factor_order_non_negative
        CHECK (
            factor_order >= 0
        ),

    CONSTRAINT ck_deal_evaluation_score_factor_status
        CHECK (
            status IN (
                'AVAILABLE',
                'UNAVAILABLE'
            )
        ),

    CONSTRAINT ck_deal_evaluation_score_factor_normalized_range
        CHECK (
            normalized_value IS NULL
            OR (
                normalized_value >= 0
                AND normalized_value <= 100
            )
        ),

    CONSTRAINT ck_deal_evaluation_score_factor_weight_range
        CHECK (
            weight >= 0
            AND weight <= 100
        ),

    CONSTRAINT ck_deal_evaluation_score_factor_contribution_range
        CHECK (
            contribution >= 0
            AND contribution <= weight
        ),

    /*
     * AVAILABLE:
     *
     * - raw_value presente;
     * - normalized_value presente.
     *
     * UNAVAILABLE:
     *
     * - raw_value ausente;
     * - normalized_value ausente;
     * - contribution = 0.
     *
     * Essa constraint impede que ausência seja silenciosamente
     * persistida como valor observado igual a zero.
     */
    CONSTRAINT ck_deal_evaluation_score_factor_availability
        CHECK (
            (
                status = 'AVAILABLE'
                AND raw_value IS NOT NULL
                AND normalized_value IS NOT NULL
            )
            OR
            (
                status = 'UNAVAILABLE'
                AND raw_value IS NULL
                AND normalized_value IS NULL
                AND contribution = 0
            )
        )
);


/* ================================================================
 * INDEXES
 * ================================================================ */

/*
 * Principal caminho para reconstrução da explicabilidade
 * de uma DealEvaluation.
 */
CREATE INDEX idx_deal_evaluation_score_factor_evaluation
    ON deal_evaluation_score_factor (deal_evaluation_id);

/*
 * Permite consultas analíticas futuras por tipo de fator.
 */
CREATE INDEX idx_deal_evaluation_score_factor_code
    ON deal_evaluation_score_factor (factor_code);
