/*
 * FASE 11-E1
 *
 * Introduz a trilha auditável dos cálculos históricos utilizados
 * para produzir momentum.
 *
 * deal_evaluation continua armazenando:
 *
 * - momentum agregado;
 * - momentum_version.
 *
 * deal_evaluation_momentum_audit preserva os fatos temporais
 * necessários para explicar e reproduzir o cálculo.
 *
 * A tabela também registra tentativas em que o momentum ficou
 * indisponível.
 */


/* ================================================================
 * MOMENTUM AUDIT
 * ================================================================ */

CREATE TABLE deal_evaluation_momentum_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    /*
     * Avaliação agregada à qual este cálculo pertence.
     *
     * Existe no máximo uma trilha de momentum para cada
     * DealEvaluation.
     */
    deal_evaluation_id BIGINT NOT NULL,

    /*
     * Versão do algoritmo que tentou produzir o momentum.
     *
     * Diferentemente de deal_evaluation.momentum_version, este campo
     * continua preenchido mesmo quando o cálculo fica indisponível.
     *
     * Exemplo:
     *
     * MOMENTUM_V1
     */
    calculation_version TEXT NOT NULL,

    /*
     * Estado do cálculo.
     *
     * AVAILABLE
     * UNAVAILABLE
     */
    status TEXT NOT NULL,

    /*
     * Explica por que um cálculo ficou indisponível.
     *
     * Exemplos atuais:
     *
     * NO_PREVIOUS_SNAPSHOT
     * SOLD_PERCENTAGE_UNAVAILABLE
     *
     * Não existe CHECK enumerando os códigos possíveis.
     * Novas versões do algoritmo poderão introduzir novos motivos
     * sem exigir alteração estrutural do schema.
     */
    unavailable_reason TEXT,

    /*
     * Snapshot imediatamente anterior utilizado como base.
     *
     * Será NULL quando ainda não existir observação histórica
     * anterior para o ASIN.
     */
    previous_offer_snapshot_id BIGINT,

    /*
     * Intervalo temporal exato entre o snapshot anterior e o
     * snapshot atual da DealEvaluation.
     *
     * Armazenamos segundos para preservar precisão e evitar perda
     * de informação em intervalos que não sejam horas inteiras.
     */
    elapsed_seconds BIGINT,

    /*
     * Diferença do percentual vendido em pontos percentuais:
     *
     * current - previous
     *
     * Pode ser positiva, negativa ou zero.
     *
     * Será NULL quando o percentual vendido não estiver disponível
     * em alguma das duas observações.
     */
    sold_percentage_delta NUMERIC,

    /*
     * Diferença absoluta do preço atual:
     *
     * current - previous
     *
     * Valor negativo representa redução de preço.
     */
    current_price_delta NUMERIC,

    /*
     * Variação percentual do preço em relação à observação anterior.
     *
     * Pode ser NULL quando o preço anterior for zero.
     */
    current_price_delta_percentage NUMERIC,

    /*
     * Diferença em pontos percentuais do melhor desconto à vista
     * reconhecido:
     *
     * current - previous
     *
     * Pode ser NULL quando alguma observação não possuir desconto
     * à vista explicitamente reconhecido.
     */
    cash_discount_delta NUMERIC,

    /*
     * Resultado produzido pelo algoritmo de momentum.
     *
     * O valor permanece NULL quando status = UNAVAILABLE.
     */
    momentum NUMERIC,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,


    /* ============================================================
     * FOREIGN KEYS
     * ============================================================ */

    CONSTRAINT fk_momentum_audit_evaluation
        FOREIGN KEY (deal_evaluation_id)
        REFERENCES deal_evaluation (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_momentum_audit_previous_snapshot
        FOREIGN KEY (previous_offer_snapshot_id)
        REFERENCES offer_snapshot (id),


    /* ============================================================
     * UNIQUENESS
     * ============================================================ */

    /*
     * Cada avaliação possui no máximo uma execução auditável
     * de momentum.
     *
     * Uma nova versão aplicada no futuro deverá produzir uma nova
     * DealEvaluation, em vez de sobrescrever silenciosamente o
     * cálculo histórico.
     */
    CONSTRAINT uq_momentum_audit_evaluation
        UNIQUE (deal_evaluation_id),


    /* ============================================================
     * STRUCTURAL CHECKS
     * ============================================================ */

    CONSTRAINT ck_momentum_audit_status
        CHECK (
            status IN (
                'AVAILABLE',
                'UNAVAILABLE'
            )
        ),

    CONSTRAINT ck_momentum_audit_elapsed_positive
        CHECK (
            elapsed_seconds IS NULL
            OR elapsed_seconds > 0
        ),

    /*
     * Snapshot anterior e intervalo temporal representam o mesmo
     * contexto histórico.
     *
     * Portanto:
     *
     * ambos existem
     *
     * ou
     *
     * ambos são NULL.
     */
    CONSTRAINT ck_momentum_audit_previous_context
        CHECK (
            (
                previous_offer_snapshot_id IS NULL
                AND elapsed_seconds IS NULL
            )
            OR
            (
                previous_offer_snapshot_id IS NOT NULL
                AND elapsed_seconds IS NOT NULL
            )
        ),

    /*
     * Sem snapshot anterior não existe comparação.
     *
     * Consequentemente, nenhum delta histórico pode existir.
     */
    CONSTRAINT ck_momentum_audit_no_previous_no_deltas
        CHECK (
            previous_offer_snapshot_id IS NOT NULL
            OR
            (
                sold_percentage_delta IS NULL
                AND current_price_delta IS NULL
                AND current_price_delta_percentage IS NULL
                AND cash_discount_delta IS NULL
            )
        ),

    /*
     * Quando existe snapshot anterior, a diferença absoluta
     * de preço sempre é calculável porque currentPrice é obrigatório
     * nas observações históricas.
     */
    CONSTRAINT ck_momentum_audit_previous_has_price_delta
        CHECK (
            previous_offer_snapshot_id IS NULL
            OR current_price_delta IS NOT NULL
        ),

    /*
     * Resultado disponível:
     *
     * - momentum presente;
     * - motivo de indisponibilidade ausente;
     * - contexto histórico anterior presente.
     *
     * Resultado indisponível:
     *
     * - momentum ausente;
     * - motivo de indisponibilidade presente.
     *
     * A constraint é deliberadamente independente de MOMENTUM_V1,
     * permitindo versões futuras.
     */
    CONSTRAINT ck_momentum_audit_availability
        CHECK (
            (
                status = 'AVAILABLE'
                AND momentum IS NOT NULL
                AND unavailable_reason IS NULL
                AND previous_offer_snapshot_id IS NOT NULL
                AND elapsed_seconds IS NOT NULL
            )
            OR
            (
                status = 'UNAVAILABLE'
                AND momentum IS NULL
                AND unavailable_reason IS NOT NULL
            )
        )
);


/* ================================================================
 * INDEXES
 * ================================================================ */

/*
 * uq_momentum_audit_evaluation já cria índice para
 * deal_evaluation_id.
 */

/*
 * Permite localizar avaliações que utilizaram um determinado
 * snapshot como referência histórica.
 */
CREATE INDEX idx_momentum_audit_previous_snapshot
    ON deal_evaluation_momentum_audit (
        previous_offer_snapshot_id
    );

/*
 * Permite consultas analíticas por versão e estado do cálculo.
 *
 * Exemplos futuros:
 *
 * quantos MOMENTUM_V1 foram calculados?
 * quantos ficaram indisponíveis?
 */
CREATE INDEX idx_momentum_audit_version_status
    ON deal_evaluation_momentum_audit (
        calculation_version,
        status
    );
